import Layout from "@/layout";
import { store } from "@/store";
import Head from "next/head";
import { Provider } from "react-redux";

export default function Home() {
  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </Provider>
  );
}
